# Generated by Django 2.1.5 on 2019-02-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_pricerange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricerange',
            name='category',
        ),
    ]
