# Generated by Django 2.1.7 on 2019-02-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_pricerange_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/image', verbose_name='图片'),
        ),
    ]
