# Generated by Django 2.1.7 on 2019-02-24 19:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0004_remove_pricerange_category'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='ShopCart',
        ),
    ]
