# Generated by Django 2.1.5 on 2019-02-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190212_0045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifycode',
            options={'verbose_name': '邮箱验证码', 'verbose_name_plural': '邮箱验证码'},
        ),
        migrations.RemoveField(
            model_name='verifycode',
            name='mobile',
        ),
        migrations.AddField(
            model_name='verifycode',
            name='email',
            field=models.EmailField(default='', max_length=50, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='verifycode',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '忘记密码')], default='register', max_length=10, verbose_name='验证码类型'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='code',
            field=models.CharField(default='', max_length=10, verbose_name='验证码'),
        ),
    ]
