# Generated by Django 2.1.5 on 2019-02-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_emailverifycode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerifyCode',
        ),
    ]
