# Generated by Django 2.1.7 on 2019-02-23 20:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_operation', '0003_delete_emailverifycode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLeavingMessage',
            new_name='UserMessage',
        ),
    ]
